version: '3.4'

services:
  php:
    container_name: 'subsmanager-php-fpm'
    network_mode: bridge
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/php:/usr/local/etc/php:ro,cached
      - .:/app:rw,cached
      - ./var:/app/var:rw,delegated
      - ./.composer:/var/www/.composer
    expose:
      - 9000
    user: '1000'
    links:
      - db

  nginx:
    container_name: 'berletek.tornazzvelem.docker'
    network_mode: bridge
    build: .docker/nginx
    ports:
      - 80:80
    volumes:
      - ./public:/app/public:ro
      - ./.docker/nginx/etc/nginx:/etc/nginx:ro,cached
    links:
      - "php"

  nodejs:
    network_mode: bridge
    build: .docker/nodejs
    volumes:
      - .:/app:rw,delegated

  db:
    container_name: 'subsmanager-db'
    network_mode: bridge
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'subsmanager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./.docker/db/data:/var/lib/mysql
